version: "3.8"
services:
  server:
    build: ./server
    depends_on:
      - client
    ports:
      - 5000:5000
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: always