apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: profile-pod
      app: profile-app
  template:
    metadata:
      name: profile-pod
      labels:
        name: profile-pod
        app: profile-app
    spec:
      containers:
      - name: profile-app
        image: barry1234/profile-service:v1
        ports:
        - containerPort: 3002
        env:
          - name: NODE_ENV
            value: test
          - name: DB_HOST
            value: mysqldb    
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: root
          - name: DB_NAME
            value: recruitapp_db
          # - name: DB_PORT
          #   value: 3306
        
---

apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30003
  selector:
    app: profile-app

