apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: client-pod
      app: client-app
  template:
    metadata:
      name: client-pod
      labels:
        name: client-pod
        app: client-app
    spec:
      containers:
      - name: client-app
        image: barry1234/client-slim
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 80
  selector:
    app: client-app

---

apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: talent-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: talentplus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 3000
  
    - host: talentserver.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 5000