apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: client-pod
      app: client-app
  template:
    metadata:
      name: client-pod
      labels:
        name: client-pod
        app: client-app
    

    spec:
      containers:
      - name: client-app
        image: docker.io/barry1234/talent-client:v1
        ports:
        - containerPort: 3000
        env:
        - name: "proxy"
          value: "http://server.default.svc.cluster.local:5000/"
  
---

apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: client-app
