apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: client-pod
      app: client-app
  template:
    metadata:
      name: client-pod
      labels:
        name: client-pod
        app: client-app
    spec:
      containers:
      - name: client-app
        image: barry1234/client-slim
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 80
  selector:
    app: client-app
